#!/usr/bin/python
import sys
from os.path import join, dirname, exists

sourcePath = join(dirname(__file__), 'lib', 'wecomp.py')
if exists(sourcePath):
	sys.path.insert(0, dirname(sourcePath))
	try:
		from wecomp import main
	finally:
		del sys.path[0]
else:
	from wecomp import main

if __name__ == '__main__':
    main()